#!/usr/bin/env bash
# displays Best School 10 times.

COUNTER=10
until [ $COUNTER -lt 1 ]
do
    echo "Best School"
    ((COUNTER-=1))
done
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
